#!/bin/bash

# ============================================================================================================================
# * Basic packages
# ============================================================================================================================
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install -y software-properties-common gconf2 gnome-panel nautilus-dropbox
sudo apt-get install -y python-software-properties g++ make xclip xsel git-flow gnupg zsh ack
sudo apt-get install -y cdargs antiword poppler-utils htop expect dnsmasq openssh-server openssh-client
sudo apt-get install -y thunderbird gimp flashplugin-installer swfdec-gnome kupfer bleachbit meld
sudo apt-get install -y transmission firefox fogger abiword vlc pidgin

# ============================================================================================================================
# * Packages from PPAs
# ============================================================================================================================
sudo add-apt-repository -y ppa:aguignard/ppa/ubuntu `# tig`
sudo add-apt-repository -y ppa:cassou/emacs `# emacs`
sudo add-apt-repository -y ppa:alexx2000/doublecmd `# double commander`
sudo add-apt-repository -y ppa:webupd8team/sublime-text-2 `# sulime text 2`
sudo apt-add-repository -y ppa:blueyed/ppa `# vim`
sudo add-apt-repository -y ppa:fkrull/deadsnakes `# python3`
sudo add-apt-repository -y ppa:eugenesan/ppa `# midnight commander`
sudo add-apt-repository -y ppa:pi-rho/dev `# tmux`
sudo add-apt-repository -y ppa:chris-lea/node.js `# nodejs`
sudo add-apt-repository -y ppa:nginx/stable `# nginx`
sudo add-apt-repository -y ppa:keepassx/daily `# keepassx`
sudo add-apt-repository -y ppa:skype-wrapper/ppa `# skype-wrapper`
sudo add-apt-repository -y ppa:dhor/myway `# xnview`
sudo add-apt-repository -y ppa:adamreichold/qpdfview-dailydeb `# qpdfview`
sudo add-apt-repository -y ppa:mamarley/quassel `# quassel`
sudo add-apt-repository -y ppa:oxan/whatpulse `# whatpulse`
sudo apt-get update && sudo apt-get upgrade

sudo apt-get install -y tig emacs-snapshot doublecmd-qt vim python3.3 python3.3-dev mc tmux xnview quassel-qt4
sudo apt-get install -y skype-wrapper sublime-text keepassx nginx git nodejs qpdfview
sudo service nginx restart
# sudo apt-get install -y gdm gnome-shell gnome-tweak-tool

# ============================================================================================================================
# * Manual install packages
# ============================================================================================================================
if [[ -z `command -v "quicktile"` ]]; then
    sudo apt-get install -y python-xlib python-dbus python-wnck
    cd /usr/local/src
    sudo git clone https://github.com/ssokolow/quicktile
    cd quicktile
    sudo ./setup.py install
    cd
fi

if [[ -z `command -v "google-chrome"` ]]; then
    sudo apt-get install -y curl libxss1 libnss3-1d
    wget -q -E https://gist.github.com/raw/4686647/ubuntu-install-google.bash -O - | sudo bash
    sudo apt-get install -y google-chrome-stable
fi

if [[ -z `command -v "gits"` ]]; then
    cd /usr/local/src
    sudo git clone git://gitslave.git.sourceforge.net/gitroot/gitslave/gitslave
    cd gitslave
    sudo make
    sudo make install -C contrib
    sudo ln -s gits /usr/local/bin/
    cd
fi

# ============================================================================================================================
# * Remove unnecessary programs
# ============================================================================================================================
sudo apt-get purge -y brasero banshee gnomine tomboy gedit gwibber aisleriot \
empathy ubuntuone-installer libreoffice-math shotwell libreoffice-draw totem rhythmbox \
evince seahorse deja-dup gnome-sudoku gbrainy libreoffice-impress sni-qt mahjongg

sudo apt-get upgrade && sudo apt-get clean && sudo apt-get autoremove

# ============================================================================================================================
# * Fonts
# ============================================================================================================================
cd $HOME/Downloads
git clone https://github.com/Lokaltog/powerline-fonts
cd powerline-fonts
mkdir -p $HOME/.fonts
mv * $HOME/.fonts/
cd ..
rm -rf powerline-fonts
fc-cache -vf $HOME/.fonts > /dev/null 2>&1

# ============================================================================================================================
# * Ruby
# ============================================================================================================================
# Install RVM
# http://sirupsen.com/get-started-right-with-rvm/
[[ -f "$HOME/.profile" ]] && rm $HOME/.profile
curl -L https://get.rvm.io | bash -s stable
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"' >> .bashrc && bash

# Install latest ruby - 2.0.0
rvm install 2.0.0
rvm use 2.0.0
rvm --default 2.0.0
rvm rubygems latest

#Installing Gem Files
# IMPORTANT: Some gems might need symilnk from /usr/bin to /bin
gemFiles="tmuxinator giternal compass"
for gemFile in $gemFiles
do
  [[ -z `command -v "${gemFile}"` ]] && gem install ${gemFile} --no-ri --no-rdoc
done