#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
brew update && brew upgrade
brew install midnight-commander zsh ack vim nginx wget
brew install git tig git-flow gitslave hub
brew install tmux wemux

wget --no-check-certificate -q -O - https://raw.github.com/iwfmp/dot-f-ings/master/install-general | sh

brew cask install google-chrome cyberduck iterm2 keepassx keyremap4macbook spectacle skype sublime-text teamviewer time-out transmission onyx quicksilver cheatsheet
# brew cask install vlc firefox filezilla burn clamxav google-drive cloudapp cord google-music-manager handbrake
# brew cask install netnewswire screenhero simple-comic skitch skim nvalt licecap adium unison tunnelblick
# brew cask install viscosity atext bartender growlnotify hazel shortcat sparrow textexpander things linkinus little-snitch path-finder postbox

# ============================================================================================================================
# * Fonts
# ============================================================================================================================
cd $HOME/Downloads
git clone https://github.com/Lokaltog/powerline-fonts
cd powerline-fonts
mv * ~/Library/Fonts/
cd ..
rm -rf powerline-fonts
