#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
brew update && brew upgrade
brew install midnight-commander zsh ack vim
brew install git tig git-flow gitslave
brew install tmux wemux

sudo gem install tmuxinator giternal compass --no-ri --no-rdoc

curl -s https://raw.github.com/fbeeper/fBootstrap/master/git/git.sh | sh

if [[ -f ~/.gitslave ]]; then
    cd $HOME
    git init
    git remote add origin git@github.com:iwfmp/dot-f-ings.git
    git pull origin master
    gits populate
fi

# Cloning submodules and install procedure
for dir in `cat .gitslave | awk {'print $2'} | tr -d '"'`
do
    cd $dir
    [[ -e .giternal.yml ]] && giternal update
    cd -
done

ln -sf $HOME/.emacs.d/init/.emacs.el $HOME/.emacs > /dev/null 2>&1
ln -sf $HOME/.git.d/init/.gitconfig $HOME/ > /dev/null 2>&1
ln -sf $HOME/.git.d/init/.tigrc $HOME/ > /dev/null 2>&1
ln -sf $HOME/.tmux/init/.tmux.conf $HOME/ > /dev/null 2>&1
ln -sf $HOME/.tmux/init/.tmux-powerlinerc $HOME/ > /dev/null 2>&1
ln -s $HOME/.zsh/init/.zlogout $HOME/ > /dev/null 2>&1
ln -s $HOME/.zsh/init/.zshenv $HOME/ > /dev/null 2>&1
ln -s $HOME/.zsh/init/.zshrc $HOME/ > /dev/null 2>&1

ln -sf $HOME/.local.d/lib/spot/spot.sh $HOME/.local.d/bin/spot > /dev/null 2>&1
ln -sf $HOME/.local.d/lib/bd/bd $HOME/.local.d/bin/bd > /dev/null 2>&1
ln -sf $HOME/.local.d/lib/fzf/fzf $HOME/.local.d/bin/fzf > /dev/null 2>&1
ln -sf $HOME/.tmux/init/powerline.sh $HOME/.tmux/lib/tmux-powerline/themes/ > /dev/null 2>&1

chsh -s /bin/zsh

cd $HOME/Downloads
curl -o Solarized-Dark.itermcolors http://www.iterm2.com/hostedcolors/Solarized%20Dark.itermcolors
defaults write net.sourceforge.iTerm Displays -dict-add Solarized-Dark < Solarized-Dark.itermcolors
BOOKMARKS=`defaults read net.sourceforge.iTerm Bookmarks | sed 's/\("Display Profile" = \)"[^"]*";/\1"Solarized-Dark";/'`
defaults write net.sourceforge.iTerm Bookmarks "$BOOKMARKS"

rm $HOME/.bash*  > /dev/null 2>&1
rm $HOME/.profile  > /dev/null 2>&1