#!/bin/bash

# Add the ability to use apt-add-repository, else it doesn't exist.
[[ -z `command -v apt-add-repository` ]] && sudo apt-get install python-software-properties

# Install git and git slave, if not yet present.
[[ -z `command -v git` ]] && sudo apt-get install -y git
if [[ -z `command -v "gits"` ]]; then
    cd /usr/local/src
    sudo git clone git://gitslave.git.sourceforge.net/gitroot/gitslave/gitslave
    cd gitslave
    sudo make
    sudo make install
fi

# Initialize git repository and prepare git slave.
if [[ -z `command -v "gits"` ]]; then
    echo "Something went wrong. Check it out, bithc."
    exit
fi

if [[ -f ~/.gitslave ]]; then
    cd $HOME
    git init
    git remote add origin git@github.com:iwfmp/dot-f-ings.git
    git pull origin master
    gits populate
fi

# Cloning submodules and install procedure
for dir in `cat .gitslave | awk {'print $2'} | tr -d '"'`
do
    cd $dir
    [[ -e .giternal.yml ]] && giternal update
    [[ -e install ]] && ./install
    cd -
done
