#!/bin/bash

# ============================================================================================================================
# * Basic packages
# ============================================================================================================================
sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install -y software-properties-common python-software-properties \
g++ gcc make xclip xsel gnupg zsh dnsmasq openssh-server vlc \
flashplugin-installer swfdec-gnome kupfer cdargs nautilus-dropbox expect

# ============================================================================================================================
# * Packages from PPAs
# ============================================================================================================================
sudo add-apt-repository -y ppa:aguignard/ppa/ubuntu `# Tig`
sudo add-apt-repository -y ppa:cassou/emacs `# Emacs`
sudo add-apt-repository -y ppa:alexx2000/doublecmd `# Double Commander`
sudo add-apt-repository -y ppa:webupd8team/sublime-text-2 `# Sublime Text 2`
sudo add-apt-repository -y ppa:fkrull/deadsnakes `# Python3`
sudo add-apt-repository -y ppa:pi-rho/dev `# Tmux`
sudo add-apt-repository -y ppa:keepassx/daily `# KeepassX`
sudo add-apt-repository -y ppa:skype-wrapper/ppa `# Skype-Wrapper`
sudo add-apt-repository -y ppa:dhor/myway `# XnView`
sudo add-apt-repository -y ppa:adamreichold/qpdfview-dailydeb `# QPdfView`
sudo add-apt-repository -y ppa:git-core/ppa `# Git`
# sudo add-apt-repository -y ppa:oxan/whatpulse `# whatpulse`
# sudo add-apt-repository -y ppa:eugenesan/ppa `# Midnight Commander`
# sudo add-apt-repository -y ppa:mamarley/quassel `# Quassel`
# sudo add-apt-repository -y ppa:ubuntu-x-swat/x-updates `# Nvidia Drivers`
sudo apt-get update

sudo apt-get install --ignore-missing -y tig emacs-snapshot python3 python3-dev \
skype-wrapper sublime-text keepassx git qpdfview mc tmux xnview doublecmd-qt
# sudo apt-get install -y nvidia-current quassel-qt4

# ============================================================================================================================
# * Manual install packages
# ============================================================================================================================
if [[ -z `command -v "quicktile.py"` ]]; then
    sudo apt-get install -y python-xlib python-dbus python-wnck
    cd /usr/local/src
    sudo git clone https://github.com/ssokolow/quicktile
    cd quicktile
    sudo ./setup.py install
    cd
fi

if [[ -z `command -v "google-chrome"` ]]; then
    sudo apt-get install -y curl libxss1 libnss3-1d
    wget -q -E https://gist.github.com/raw/4686647/ubuntu-install-google.bash -O - | sudo bash
    sudo apt-get install -y google-chrome-stable
fi

if [[ -z `command -v "gits"` ]]; then
    cd /usr/local/src
    sudo git clone git://gitslave.git.sourceforge.net/gitroot/gitslave/gitslave
    cd gitslave
    sudo make
    sudo make install -C contrib
    sudo ln -s /usr/local/src/gitslave/gits /usr/local/bin/
    cd
fi

# ============================================================================================================================
# * Remove unnecessary programs
# ============================================================================================================================
sudo apt-get purge --ignore-missing -y brasero banshee tomboy gedit gwibber xul-ext-ubufox \
empathy ubuntuone-installer libreoffice-math shotwell libreoffice-draw totem rhythmbox aisleriot \
evince seahorse deja-dup gnome-sudoku gbrainy libreoffice-impress sni-qt gnome-mahjongg \
transmission-gtk unity-scope-gdrive cheese thunderbird gnome-mines remmina firefox webbrowser-app

sudo apt-get autoclean && sudo apt-get autoremove

# ============================================================================================================================
# * Fonts
# ============================================================================================================================
cd $HOME/Downloads
git clone https://github.com/Lokaltog/powerline-fonts
cd powerline-fonts
mkdir -p $HOME/.fonts
mv * $HOME/.fonts/
cd ..
rm -rf powerline-fonts
fc-cache -vf $HOME/.fonts > /dev/null 2>&1

# ============================================================================================================================
# * Ruby
# ============================================================================================================================
# Install RVM
# http://sirupsen.com/get-started-right-with-rvm/
[[ -f "$HOME/.profile" ]] && rm $HOME/.profile
curl -L https://get.rvm.io | bash -s stable
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"' >> $HOME/.bashrc && bash
source "$HOME/.rvm/scripts/rvm"

# Install latest ruby - 2.1.1
rvm install 2.1.1
rvm use 2.1.1
rvm --default 2.1.1
rvm rubygems latest

#Installing Gem Files
# IMPORTANT: Some gems might need symilnk from /usr/bin to /bin
echo "install: --no-rdoc --no-ri --user\nupdate: --no-rdoc --no-ri" > $HOME/.gemrc
gem install bundler berkshelf
gem install tmuxinator giternal compass fzf

# Needed because compass uses cutting edge bullshit
yes | gem uninstall --force --all sass
gem install sass

# ============================================================================================================================
# * DsnMasq
# ============================================================================================================================
# http://ihaveabackup.net/2012/06/28/using-wildcards-in-the-hosts-file/
# http://xip.io/

sudo sed -i "s/dns=/#dns=/g" /etc/NetworkManager/NetworkManager.conf
sudo sed -i '/address=/c\address=\/.dev\/127.0.0.1' /etc/dnsmasq.conf

sudo fuser -k 80/tcp
sudo restart network-manager
sudo service dnsmasq restart
