#!/bin/bash

xcode-select --install
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
brew update && brew upgrade
brew install midnight-commander zsh ack vim nginx
brew install git tig git-flow gitslave hub
brew install tmux wemux

bash $HOME/install-general

brew cask install google-chrome cyberduck iterm2 keepassx keyremap4macbook spectacle skype sublime-text teamviewer time-out transmission onyx quicksilver
brew cask install vlc firefox filezilla burn clamxav google-drive cloudapp cord google-music-manager handbrake
brew cask install netnewswire screenhero simple-comic skitch skim nvalt licecap adium unison tunnelblick
brew cask install viscosity atext bartender growlnotify hazel shortcat sparrow textexpander things linkinus little-snitch path-finder postbox

cd $HOME/Downloads
curl -o Solarized-Dark.itermcolors http://www.iterm2.com/hostedcolors/Solarized%20Dark.itermcolors
defaults write net.sourceforge.iTerm Displays -dict-add Solarized-Dark < Solarized-Dark.itermcolors
BOOKMARKS=`defaults read net.sourceforge.iTerm Bookmarks | sed 's/\("Display Profile" = "[^"]*";/\1"Solarized-Dark";/'`
defaults write net.sourceforge.iTerm Bookmarks "$BOOKMARKS"