#!/bin/bash

cd $HOME
for dir in `cat .gitslave | awk {'print $2'} | tr -d '"'`
do
  rm -rf $dir
done
rm `git ls-tree -r master --name-only`
rm -rf .git
find -L $HOME -type l -delete

# Remove Gnome config
rm -rf .gnome .gnome2 .gnome3 .gconf .gconfd .metacity .cache .dbus .dmrc .mission-control .config/dconf/user