#!/usr/bin/env bash
set -eu

# Ask for the administrator password upfront
sudo -v

for dir in `cat .gitslave | awk {'print $2'} | tr -d '"'`
do
    cd $dir
    echo "======== Updating: $dir Plugins ========"
    [[ -e .giternal.yml ]] && giternal update
    cd -
done

echo "======== Updating: Homebrew Apps/Casks ========"
brew update && brew upgrade && brew cleanup && brew cask cleanup

echo "======== Updating: Ruby Gems ========"
sudo gem update --no-ri --no-rdoc

echo "======== Updating: Vagrant Plugins ========"
vagrant plugin update