#!/bin/bash

scriptDir=`pwd`

# Cloning submodules and install procedure
programVars="tmux mc slmenu"
for programVar in $programVars
do
	cd /usr/local/share/${programVar}
  sudo git pull || sudo hg pull
  if [[ `sudo git fetch && git rev-list HEAD...origin/master --count` > 0 ]]; then
  	[[ -e "autogen.sh" ]] && sudo ./autogen.sh
  	[[ -e "configure" ]] && sudo ./configure --prefix=/usr/local
  	[[ -e "makefile" ]] && sudo make &&	sudo make clean install
  fi
done

cd $scriptDir
for dir in `cat .gitslave | awk {'print $2'} | tr -d '"'`
do
  cd $dir
  [[ -e .gitmodules ]] && git submodule foreach git pull origin master && git commit -a -m "updating plugins"
  [[ -e update ]] && ./update
  cd -
done